### ISSUE TITLE
ES5 builds don't generate index.html file

### ISSUE THREAD

**Issue by Chisnet** [rdkcentral/Lightning-CLI#118]
When running the dist command with the --es5 argument supplied the outputted bundle does not include an index.html file.

`lng dist --es5`

The ES6 bundles appear to generate correctly and include the correct index.html output.

Using CLI version 2.4.0 on a Mac

**Comment by Chisnet** [comment]
Seems this only happens if the target folder already exists, if it's not present all files are created correctly

**Comment by michielvandergeest** [comment]
This is by design. The dist command is intended to generate a distributable version of the App for self hosting where you can customize the index.html to fit your situation. The complete file structure is only created when the dist folder for your target environment (es5 or es6) doesn't exist yet.

See also: https://rdkcentral.github.io/Lightning-CLI/#/commands/dist
