### ISSUE TITLE
Create generates App.js with License in it

### ISSUE THREAD

**Issue by chiefcll** [rdkcentral/Lightning-CLI#226]
https://github.com/rdkcentral/Lightning-CLI/blob/master/fixtures/ts/lightning-app/src/App.ts#L5

Should the JS files that a CLI create include a license? Should it be removed from the TS and JS files?

**Comment by michielvandergeest** [comment]
Hey Chris, good question.

Initially these fixtures files didn't have any license included, because to your point, it doesn't really make sense to start a new project with license headers from Metrological. They were added by someone from RDK central, as the files are considered copyrighted code.

I would be totally in favour of removing them in this instance, though. Can we get your opinion / approval on this @mhughesacn?

An alternative (although not really desirable) would be to add an extra step during `lng create` that removes these headers from the newly created project after the fixtures have been copied.

**Comment by mhughesacn** [comment]
Hi Michiel/Chris: Please forgive my ignorance: I think "lng create" lets you create a new App, and it uses the ts files as a template to set up the files you need.  Your issue is that your newly created app now gets populated with Metrological copyrights which you feel don't belong.  Is this correct?

**Comment by chiefcll** [comment]
Yes that is correct. Either the ts or js folders are used for Typescript or Javascript. They stub out a new project for clients and the App.js it creates includes the Metro copyrights which then leads to the question does anything a user creates copyrighted by Metro?

**Comment by mhughesacn** [comment]
Thanks Chris.

If the material which is copied into your new project is small (structural stuff rather than large blobs of functional code), we could regard it as similar to what an IDE provides, and leave out the copyright.  The Metrological header would be replaced by a one-line comment on the lines of "Framework provided by Lightning-CLI" etc. if that makes sense.  Code which doesn't fit that description would keep its header.

If you are happy with this, please will you give me a list of the files which would lose their Metrological copyrights.  Depending on this, I may need to look for approval from RDKM.

**Comment by chiefcll** [comment]
It's just the two files:

https://github.com/rdkcentral/Lightning-CLI/blob/master/fixtures/ts/lightning-app/src/App.ts#L5
https://github.com/rdkcentral/Lightning-CLI/blob/master/fixtures/js/lightning-app/src/App.js

Should I open a PR for this?

**Comment by michielvandergeest** [comment]
It would be great if we can lose the license header for these 2 files, as the code in them is really just boilerplate stuff.

Yes, please make a PR for this Chris.

Tagging @uguraslan as well, so we can still get this in for our April release.

**Comment by chiefcll** [comment]
@mhughesacn - I think its best to not have anything at all there. That whole directory JS / TS gets copied to create a new project.

**Comment by mhughesacn** [comment]
@chiefcll - I don't have a problem with this and the pull req removes the only two headers in scope.  Everything under "fixtures" can be considered boilerplate framework.
