### ISSUE TITLE
Configure root / dist

### ISSUE THREAD

**Issue by mattiapontonio** [rdkcentral/Lightning-CLI#55]
Should be good if I can specify optionally the path in the system of the dist folder.
This is because I have an express server and I need to configure the static root.
https://expressjs.com/it/starter/static-files.html

## My goal
1 Express server
- `/` --> point to the `dist` and serves the SPA app.
- `/api/something` --> point to my custom APIs
- same hostname and port
- I want even to make the server and the client as 2 different npm modules

**Comment by michielvandergeest** [comment]
We will not make the `dist` or `build` folder configurable, because it introduces more complexity.

You may however benefit of the new `lng dist` command (available as of version _1.6.0_). It's intended use is to generate distributable versions of the App that you can move to the correct folder location or a webserver yourself.
