### ISSUE TITLE
Locally installed application does not work - (startApp.js:113 Uncaught (in promise) TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by dwrobel** [rdkcentral/Lightning-CLI#61]
Applications launched from local storage (using file:// locator) does not work.
Chrome, _Version 83.0.4103.61 (Official Build) (64-bit)_ generates the following message/errors:
```
startApp.js:130 Fetch API cannot load file:///home/sw/public_html/refapp2-2/settings.json. URL scheme must be "http" or "https" for CORS request.
getSettings @ startApp.js:130
(anonymous) @ startApp.js:46
(anonymous) @ startApp.js:221
Promise.then (async)
(anonymous) @ startApp.js:218
sequence @ startApp.js:213
startApp @ startApp.js:41
(anonymous) @ startApp.js:251
startApp.js:137 No settings.json found. Using defaults.
(anonymous) @ startApp.js:137
Promise.catch (async)
getSettings @ startApp.js:134
(anonymous) @ startApp.js:46
(anonymous) @ startApp.js:221
Promise.then (async)
(anonymous) @ startApp.js:218
sequence @ startApp.js:213
startApp @ startApp.js:41
(anonymous) @ startApp.js:251
startApp.js:113 Fetch API cannot load file:///home/sw/public_html/refapp2-2/metadata.json. URL scheme must be "http" or "https" for CORS request.
getAppMetadata @ startApp.js:113
(anonymous) @ startApp.js:56
(anonymous) @ startApp.js:221
Promise.then (async)
(anonymous) @ startApp.js:218
sequence @ startApp.js:213
startApp @ startApp.js:41
(anonymous) @ startApp.js:251
startApp.js:113 Uncaught (in promise) TypeError: Failed to fetch
    at getAppMetadata (startApp.js:113)
    at startApp.js:56
    at startApp.js:221
getAppMetadata @ startApp.js:113
(anonymous) @ startApp.js:56
(anonymous) @ startApp.js:221
Promise.then (async)
(anonymous) @ startApp.js:218
sequence @ startApp.js:213
startApp @ startApp.js:41
(anonymous) @ startApp.js:251
```

**Comment by michielvandergeest** [comment]
This error is caused by browser policies that don’t allow `fetch` or `xhr` requests from the local filesystem. It exists as a security measure.

`startApp.js` uses fetch to dynamically load settings and metadata, simulating the way the Metrological App Store works during local development.

We recently released version _1.6.0_ of the Lightning CLI that introduces a new `lng dist` command (https://github.com/rdkcentral/Lightning-CLI#dist). `lng dist` generates a distributable version of the App and doesn’t reply on `startApp.js`, so that should solve this exact issue.

_However_ as soon as the App code itself uses `fetch` or `xhr` to retrieve data, you will run into the same issue. For that reason it is recommended to always run Apps using a (local) webserver.
