### ISSUE TITLE
Support Typescript

### ISSUE THREAD

**Issue by gajjargaurav** [rdkcentral/Lightning-CLI#94]
Feature Request: Lightning is really good. I would love if it supported development in Typescript

**Comment by mattbadley** [comment]
I want this feature too!

**Comment by richardforjoe** [comment]
+1

**Comment by ka3na** [comment]
+1

**Comment by newmanja** [comment]
+1

**Comment by erikhaandrikman** [comment]
CLI version [2.3.4](https://www.npmjs.com/package/@lightningjs/cli/v/2.3.4) ships support for a new bundler [esbuild](https://esbuild.github.io/). This bundler supports TypeScript out of the box. However, it does not do any typechecking:  https://esbuild.github.io/content-types/#typescript

Since this is an experimental feature you need to explicitly enable it: https://rdkcentral.github.io/Lightning-CLI/#/environmentvariables?id=lng_app_bundler

**Comment by CooperCao** [comment]
+1

**Comment by CooperCao** [comment]
> [esbuild](https://esbuild.github.io/).

I use esbuild, same code , only change build type. but can't run. CLI-VERSION:2.4
![image](https://user-images.githubusercontent.com/14977519/115806699-d59e6f80-a419-11eb-889c-81184209a8ca.png)

**Comment by JanSunavec** [comment]
TS for Rollup https://github.com/rdkcentral/Lightning-CLI/pull/140

**Comment by michaelgosling** [comment]
> CLI version [2.3.4](https://www.npmjs.com/package/@lightningjs/cli/v/2.3.4) ships support for a new bundler [esbuild](https://esbuild.github.io/). This bundler supports TypeScript out of the box. However, it does not do any typechecking: https://esbuild.github.io/content-types/#typescript
> 
> Since this is an experimental feature you need to explicitly enable it: https://rdkcentral.github.io/Lightning-CLI/#/environmentvariables?id=lng_app_bundler

even when enabling this, there's an error produced on this line when the cli tries to parse a type annotation
https://github.com/rdkcentral/Lightning-CLI/blob/master/src/helpers/esbuildbabel.js#L60

**Comment by sandeep-vedam** [comment]
Basic Typescript support is enabled with version 2.8.0 of CLI
